version: '3.9'
services:
  backend:
    volumes:
      - .:/app
    build:
      context: .
    ports: 
      - '8080:8000'
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
    - POSTGRES_DB=$POSTGRES_DB
    - POSTGRES_USER=$POSTGRES_USER
    - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    - POSTGRES_HOST=$POSTGRES_HOST
    - POSTGRES_PORT=$POSTGRES_PORT
    ports:
      - "${POSTGRES_PORT}"

volumes:
  db-data:
