services:
  backend:
    volumes:
      - .:/app
    build:
      context: .
    ports: 
      - '8080:8000'
  db:
    image: postgres:15-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432'

volumes:
  db-data:
