name: Build a Docker Image & Publish to GitHub Packages

on:
  push:
    branches: [ "DEV-138-git-hub-actions-backend-budowanie-obrazu-dockera-i-wypchniecie-do-ghcr" ]
  pull_request:
    branches: [ "DEV-138-git-hub-actions-backend-budowanie-obrazu-dockera-i-wypchniecie-do-ghcr" ]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
    
      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Prepare envs
        run: |
          echo DATESTAMP="$(date +'%Y%m%d')" >> $GITHUB_ENV
          echo GIT_HASH_SHORT="$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.DATESTAMP }}-${{ env.GIT_HASH_SHORT }}
          labels: |
            triggered-by=github-action-cicd

      - name: Build the Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          labels: ${{ steps.meta.outputs.labels }}

